### ISSUE TITLE
Make Maven Properties updatable

### ISSUE THREAD

**Issue by geoand** [atomist/sdm-pack-spring#15]
Hi,

I was looking into being able to change arbitrary maven properties using the `PropertiesGrammar`.

I initially believed that writing something like:

```
import {logger} from "@atomist/automation-client/internal/util/logger";
import {doWithUniqueMatch} from "@atomist/automation-client/project/util/parseUtils";
import {PropertiesGrammar} from "@atomist/sdm-pack-spring/dist/support/maven/parse/grammar/mavenGrammars";
import {SimpleProjectEditor} from "@atomist/automation-client/operations/edit/projectEditor";

export function setMavenPropertyEditor(name: string, value: string): SimpleProjectEditor {
  return p => {
    return doWithUniqueMatch(p, "**/pom.xml", PropertiesGrammar, m => {
      const matchingProperty = m.properties.find(prop => prop.name === name);
      if (matchingProperty) {
        logger.info("Changing value of '%s' from '%s' to '%s'", name, matchingProperty.value, value);
        matchingProperty.value = value;
      } else {
        logger.info("Adding property '%s' with value '%s'", name, value);
        m.properties.push({name: name, value: value});
      }
    });
  };
}
```

would do the trick.
However it doesn't seem to work since the properties seem to be read-only. 

Essentially I would love to be able to change the property value in the same fashion as the `version` can be changed for the `DependencyGrammar`.

I would be willing to work on this, I would just like some pointers in the right direction since I am not very knowledgeable of either TypeScript or grammars.

Thanks!

**Comment by johnsonr** [comment]
Interesting. Can you please provide an example of a change you'd like to make?

**Comment by geoand** [comment]
Sure thing,

The simplest use case I have in mind is when a Spring Boot project doesn't use a parent pom, but instead just includes the BOM directly, and the version of the BOM is defined in a Maven property (something like [this](https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/html/using-boot-build-systems.html#using-boot-maven-without-a-parent), but with the version not being hard-coded).

Does that make sense?
Thanks

**Comment by johnsonr** [comment]
I introduced path expression based XML support last week and have reimplemented the existing code on this. It's significantly superior to the microgrammar-based approach for XML.

Please take a look now, this should be quite easy.

As a model,

```typescript
export const SetSpringBootVersionTransform: CodeTransform<{ desiredBootVersion: string }> =
    async (p, ctx) =>
        doWithAllMatches(p, new XmldocFileParser(),
            "**/pom.xml",
            "//parent/version",
            n => {
                n.$value = ctx.parameters.desiredBootVersion;
            });
```

Thanks for raising this issue!

**Comment by geoand** [comment]
Thanks for resolving this!

Likes slick, I'll definitely update our project to use the new
functionality.

**Comment by johnsonr** [comment]
Cool! @lievendoclo and I have been overhauling this project quite a bit, and it's getting nice now.
Next step is adding primitives for adding imports, annotations etc so we can reproduce the Spring guides as transforms.

**Comment by geoand** [comment]
Soungs great, looking forward to the improvements 😎!
