### ISSUE TITLE
Incremental version upgrade support

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-pack-spring#17]
Issue moved from atomist/sdm#292

Created by @johnsonr at 2018-03-30T10:56:19Z:

Imagine trying to upgrade a Spring Boot 1.4.3 repo to Spring Boot 2.0.0. Unsurprisingly, the build breaks.

Atomist can then try previous versions, e.g. 1.4.4+, showing the latest that works.

**Comment by lievendoclo** [comment]
Would be interesting if there was a service that could tell you based on semantic version rules which updates should work without a hitch. For example 1.4.3 to 1.4.7 should not be an issue, 1.5.2 might be. We could write a command for this: 
`atomist give semantic updates`
and the reply would be:
`spring-boot-starter: latest bugfix: 1.4.7, latest minor: 1.5.7, latest major: 2.0.4`
