### ISSUE TITLE
Readme title doesn't get updated when using spring-team/spring-rest-seed

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-pack-spring#26]
Probably an issue with the seed, as the unit tests in this repo work. Regex in `ReplaceReadmeTitle` may need to change.

**Comment by cdupuis** [comment]
@johnsonr, turns that's a bug in `SeedDrivenGeneratorParametersSupport` at all. 

```
       if (!this.config) {
            throw new Error("config must be supplied to get source from parameters object");
        }
```

^ that line executes because we are not setting the `config` any longer on params. Probably easiest for you to address in SDM?

**Comment by johnsonr** [comment]
Fixed
