### ISSUE TITLE
Consider adding user-agent header for requests to start.spring.io

### ISSUE THREAD

**Issue by snicoll** [atomist/sdm-pack-spring#39]
As [noted in the reference documentation](https://docs.spring.io/initializr/docs/current/reference/htmlsingle/#metadata-format), we advise clients to the service to set a `User-Agent` header for each request.

`atomist/X.Y.Z` looks an obvious candidate (perhaps too general), where `X.Y.Z` is the version of the client.

Thank you.

**Comment by cdupuis** [comment]
Hey @snicoll, welcome. That sounds like a reasonable request. I guess this is used for reporting etc? 

In any case, we get this done. 

@lievendoclo, can you get this in?

**Comment by snicoll** [comment]
>  I guess this is used for reporting etc

Correct.

**Comment by snicoll** [comment]
@cdupuis @lievendoclo any feedback on this please? ☝️

**Comment by lievendoclo** [comment]
Hi @snicoll, we're going to change this into some more generic. It's going to be `atomist/sdm-pack=-spring-<version>`, instead of the name of the SDM itself

**Comment by snicoll** [comment]
OK. Where can I track that change (as this issue is closed)?

**Comment by lievendoclo** [comment]
It's covered in the PR for #40: #43
