### ISSUE TITLE
Consider reading defaults from metadata rather than hardcoding them

### ISSUE THREAD

**Issue by snicoll** [atomist/sdm-pack-spring#40]
As far as I understand, the defaults for various elements are not read from the metadata but are hard-coded. 

If I got this right, it would be better to read defaults from the service itself. This is especially important for the Spring Boot versions that change quite often. See also [the documentation](https://docs.spring.io/initializr/docs/current/reference/htmlsingle/#_content)

**Comment by cdupuis** [comment]
Another good one. Thanks for the pointer.
