### ISSUE TITLE
Use 127.0.0.1 rather than localhost or os.hostname()

### ISSUE THREAD

**Issue by ddgenome** [atomist/sdm-pack-spring#61]
When referring to the current machine in URLs, use 127.0.0.1 rather than localhost or the return value of `os.hostname()`. It is safer and should always be routable.

**Comment by lievendoclo** [comment]
Or use something like atomist.127.0.0.1.xip.io. That way you can also do name matching if needed.

**Comment by cdupuis** [comment]
No, please not. That xip.io stuff doesn't work for a lot of people.

**Comment by ddgenome** [comment]
https://github.com/atomist/sdm-pack-spring/blob/30466a1638ea12e051a055d02b1b4bfe79cd90f1/lib/java/deploy/MavenPerBranchSpringBootDeploymentGoal.ts#L116
