### ISSUE TITLE
Add up to date Kotlin seed

### ISSUE THREAD

**Issue by johnsonr** [atomist/sdm-pack-spring#79]
Generate one from Initializr

**Comment by ddgenome** [comment]
It appears the seed is dynamically generated from start.spring.io as part of the generation process.

https://github.com/atomist/sdm-pack-spring/blob/master/lib/spring/generate/springInitializrGenerator.ts

Is that not what you are seeing? @lievendoclo may have more insight here.

**Comment by ddgenome** [comment]
That is in the atomist-seeds/spring-sdm project, not here. Is it OK to keep it there and add the Kotlin one there or would you prefer them both be here?

**Comment by johnsonr** [comment]
The Kotlin seed should be in atomist-seeds

**Comment by ddgenome** [comment]
Where do you want the generators?

**Comment by ddgenome** [comment]
Issue moved to atomist-seeds/spring-sdm#23
