### ISSUE TITLE
Using `package` in a top comment of a seed project file breaks package renaming in generator

### ISSUE THREAD

**Issue by lievendoclo** [atomist/sdm-pack-spring#8]

**Comment by lievendoclo** [comment]
For example in https://github.com/spring-projects/spring-petclinic/blob/master/src/main/java/org/springframework/samples/petclinic/model/package-info.java, the top comment contains the word `package` which makes Atomist think that there is a package called `represent`. This will result in the highest common package being the root package, effectively nullifying the package renaming feature of the generator.

**Comment by johnsonr** [comment]
The solution is to switch from using a microgrammar to using an Antlr-backed path expression like the rest of the Spring pack does. That won't be fooled by comments.

**Comment by johnsonr** [comment]
Should be fixed
